basePath: /api/v1
definitions:
  challenge-backend-1_internal_model.ErrorResponse:
    properties:
      err:
        type: string
      msg:
        type: string
      ok:
        type: boolean
    type: object
  challenge-backend-1_internal_model.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/challenge-backend-1_internal_model.UserResponse'
    type: object
  challenge-backend-1_internal_model.LoginUserRequest:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 100
        type: string
    required:
    - email
    - password
    type: object
  challenge-backend-1_internal_model.UserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  challenge-backend-1_internal_model.WebResponse-challenge-backend-1_internal_model_LoginResponse:
    properties:
      data:
        $ref: '#/definitions/challenge-backend-1_internal_model.LoginResponse'
      ok:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: Challenge Backend 1
  title: Challenge Backend 1
  version: 1.0.0
paths:
  /session:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Login User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/challenge-backend-1_internal_model.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/challenge-backend-1_internal_model.WebResponse-challenge-backend-1_internal_model_LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/challenge-backend-1_internal_model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/challenge-backend-1_internal_model.ErrorResponse'
      summary: Login user
      tags:
      - User API
    put:
      consumes:
      - application/json
      description: Replace expired access_token with the new one
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/challenge-backend-1_internal_model.WebResponse-challenge-backend-1_internal_model_LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/challenge-backend-1_internal_model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/challenge-backend-1_internal_model.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh access token
      tags:
      - User API
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
